MiAuto0Km/Controllers/ContactoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MiAuto0Km;

namespace MiAuto0Km.Controllers
{
    public class ContactoesController : Controller
    {
        private cerokmdbEntities db = new cerokmdbEntities();

        // GET: Contactoes
        public ActionResult Index()
        {
            return View(db.Contactoes.ToList());
        }

        // GET: Contactoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contacto contacto = db.Contactoes.Find(id);
            if (contacto == null)
            {
                return HttpNotFound();
            }
            return View(contacto);
        }

        // GET: Contactoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contactoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Contacto,Nombre,Email,Telefono,Asunto,Comentario")] Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                db.Contactoes.Add(contacto);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(contacto);
        }

        // GET: Contactoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contacto contacto = db.Contactoes.Find(id);
            if (contacto == null)
            {
                return HttpNotFound();
            }
            return View(contacto);
        }

        // POST: Contactoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Contacto,Nombre,Email,Telefono,Asunto,Comentario")] Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contacto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contacto);
        }

        // GET: Contactoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contacto contacto = db.Contactoes.Find(id);
            if (contacto == null)
            {
                return HttpNotFound();
            }
            return View(contacto);
        }

        // POST: Contactoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contacto contacto = db.Contactoes.Find(id);
            db.Contactoes.Remove(contacto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MiAuto0Km/Controllers/VehiculoConcesionariasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MiAuto0Km;

namespace MiAuto0Km.Controllers
{
    public class VehiculoConcesionariasController : Controller
    {
        private cerokmdbEntities db = new cerokmdbEntities();

        // GET: VehiculoConcesionarias
        [Authorize]
        public ActionResult Index()
        {
            var vehiculoConcesionarias = db.VehiculoConcesionarias.Include(v => v.Concesionaria).Include(v => v.Vehiculo);
            return View(vehiculoConcesionarias.ToList());
        }

        // GET: VehiculoConcesionarias/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehiculoConcesionaria vehiculoConcesionaria = db.VehiculoConcesionarias.Find(id);
            if (vehiculoConcesionaria == null)
            {
                return HttpNotFound();
            }
            return View(vehiculoConcesionaria);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MiAuto0Km/Controllers/VehiculoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MiAuto0Km;

namespace MiAuto0Km.Controllers
{
    public class VehiculoesController : Controller
    {
        private cerokmdbEntities db = new cerokmdbEntities();



        // GET: Vehiculoes/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Marca_Id = new SelectList(db.Marcas, "ID_Marca", "Nombre_Marca");
            ViewBag.Tipo_Auto_Id = new SelectList(db.TipoAutoes, "ID_Tipo_Auto", "Descripion");
            ViewBag.TipoTransmision_id = new SelectList(db.TipoTransmisions, "ID_TipoTransmision", "Descripcion");
            return View();
        }

        // POST: Vehiculoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Auto,Descripcion,Tipo_Auto_Id,TipoTransmision_id,Marca_Id,MotorCC,Modelo,Anho")] Vehiculo vehiculo)
        {
            if (ModelState.IsValid)
            {
                db.Vehiculoes.Add(vehiculo);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.Marca_Id = new SelectList(db.Marcas, "ID_Marca", "Nombre_Marca", vehiculo.Marca_Id);
            ViewBag.Tipo_Auto_Id = new SelectList(db.TipoAutoes, "ID_Tipo_Auto", "Descripion", vehiculo.Tipo_Auto_Id);
            ViewBag.TipoTransmision_id = new SelectList(db.TipoTransmisions, "ID_TipoTransmision", "Descripcion", vehiculo.TipoTransmision_id);
            return View(vehiculo);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MiAuto0Km/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MiAuto 0Km</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/about-style.css")
    @Styles.Render("~/Content/banner.css")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mi Auto Okm", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Pagina principal", "Index", "Home")</li>
                    <li>@Html.ActionLink("Nosotros", "About", "Home")</li>
                    <li>@Html.ActionLink("Contáctenos", "Create", "Contactoes")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Concesionarias", "Index", "Concesionarias")</li>
                        <li>@Html.ActionLink("Agregar vehículo", "Create", "Vehiculoes")</li>
                        <li>@Html.ActionLink("Precios", "Index", "VehiculoConcesionarias")</li>
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MiAuto 0Km</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>